#!/bin/sh

agar_path="libs/agar"
agar_version="1.3.3"

if [ "`agar-config --sdl`" = "yes" ] ;then
	return 0
fi

cd $agar_path && \
tar -xvf "agar-"$agar_version".tar.gz" && \
cd "agar-"$agar_version && \
./configure --with-manpages=no --enable-threads=no --enable-gui=yes --enable-math=no --enable-utf8=yes --enable-network=no --with-gl=no --with-jpeg=yes --with-freetype=yes && \
make && \
make install clean && \
rm -rfv * \
return 0

echo "Error occurred while making in "$agar_path
return 1
